-- V2 seed incidents lost branch_name when device_id was dropped in V7.
-- Delete them and re-seed with complete data.
DELETE FROM incident_cameras WHERE incident_id IN (SELECT id FROM incidents WHERE branch_name IS NULL);
DELETE FROM incidents WHERE branch_name IS NULL;

INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Taman Ismail Marzuki',       'CAM 1 - Lounge Area', 'Jakarta',   'Jakarta Pusat',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '12' HOUR - INTERVAL '30' MINUTE, SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '12' HOUR - INTERVAL '10' MINUTE, LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Jakarta Pamulang',           'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Selatan',   'UNAUTHORIZED_ACCESS', 'MEDIUM', 'RESOLVED', 'A customer has entered the Teller area.',       SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '13' HOUR - INTERVAL '30' MINUTE, SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '13' HOUR - INTERVAL '18' MINUTE, LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KC Jakarta Daan Mogot',          'CAM 1 - ATM Area',    'Jakarta',   'Jakarta Barat',     'ATM_LOITERING',       'MEDIUM', 'RESOLVED', 'Someone is at the ATM for an extended period.', SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '14' HOUR - INTERVAL '30' MINUTE, SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '14' HOUR - INTERVAL '25' MINUTE, LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Tangerang Villa Melati Mas', 'CAM 3 - Lounge Area', 'Tangerang', 'Tangerang Selatan', 'AFTER_HOURS',         'LOW',    'RESOLVED', 'Detecting activity at a closed branch.',        SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '5' HOUR  - INTERVAL '30' MINUTE, SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '5' HOUR  - INTERVAL '27' MINUTE, LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KC Jakarta Pondok Kelapa',       'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Timur',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '15' HOUR - INTERVAL '50' MINUTE, SYSTIMESTAMP - INTERVAL '3' DAY - INTERVAL '15' HOUR - INTERVAL '38' MINUTE, LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Jakarta Tomang',             'CAM 1 - Lounge Area', 'Jakarta',   'Jakarta Barat',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        SYSTIMESTAMP - INTERVAL '2' DAY - INTERVAL '1' HOUR,                         SYSTIMESTAMP - INTERVAL '2' DAY - INTERVAL '40' MINUTE,                      LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Jakarta R.S. Pelni',         'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Barat',     'UNAUTHORIZED_ACCESS', 'MEDIUM', 'RESOLVED', 'A customer has entered the Teller area.',       SYSTIMESTAMP - INTERVAL '2' DAY - INTERVAL '2' HOUR,                         SYSTIMESTAMP - INTERVAL '2' DAY - INTERVAL '1' HOUR  - INTERVAL '30' MINUTE, LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KC Jakarta Pluit Selatan',       'CAM 1 - ATM Area',    'Jakarta',   'Jakarta Utara',     'ATM_LOITERING',       'MEDIUM', 'RESOLVED', 'Someone is at the ATM for an extended period.', SYSTIMESTAMP - INTERVAL '2' DAY - INTERVAL '30' MINUTE,                      SYSTIMESTAMP - INTERVAL '2' DAY - INTERVAL '10' MINUTE,                      LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Jakarta Kelapa Gading',      'CAM 3 - Lounge Area', 'Jakarta',   'Jakarta Utara',     'AFTER_HOURS',         'LOW',    'RESOLVED', 'Detecting activity at a closed branch.',        SYSTIMESTAMP - INTERVAL '4' DAY - INTERVAL '16' HOUR - INTERVAL '20' MINUTE, SYSTIMESTAMP - INTERVAL '4' DAY - INTERVAL '16' HOUR,                        LOWER(RAWTOHEX(SYS_GUID())));
INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Jakarta Graha Rekso',        'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Pusat',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        SYSTIMESTAMP - INTERVAL '4' DAY - INTERVAL '16' HOUR - INTERVAL '40' MINUTE, SYSTIMESTAMP - INTERVAL '4' DAY - INTERVAL '16' HOUR - INTERVAL '20' MINUTE, LOWER(RAWTOHEX(SYS_GUID())));
