-- V2 seed incidents lost branch_name when device_id was dropped in V7.
-- Delete them and re-seed with complete data.
DELETE FROM incident_cameras WHERE incident_id IN (SELECT id FROM incidents WHERE branch_name IS NULL);
DELETE FROM incidents WHERE branch_name IS NULL;

INSERT INTO incidents (branch_name, camera_name, region, area_group, type, severity, status, activity, detected_at, cleared_at, clear_token) VALUES
  ('KCP Taman Ismail Marzuki',       'CAM 1 - Lounge Area', 'Jakarta',   'Jakarta Pusat',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        NOW() - INTERVAL '3 days 12 hours 30 minutes', NOW() - INTERVAL '3 days 12 hours 10 minutes', gen_random_uuid()::text),
  ('KCP Jakarta Pamulang',           'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Selatan',   'UNAUTHORIZED_ACCESS', 'MEDIUM', 'RESOLVED', 'A customer has entered the Teller area.',       NOW() - INTERVAL '3 days 13 hours 30 minutes', NOW() - INTERVAL '3 days 13 hours 18 minutes', gen_random_uuid()::text),
  ('KC Jakarta Daan Mogot',          'CAM 1 - ATM Area',    'Jakarta',   'Jakarta Barat',     'ATM_LOITERING',       'MEDIUM', 'RESOLVED', 'Someone is at the ATM for an extended period.', NOW() - INTERVAL '3 days 14 hours 30 minutes', NOW() - INTERVAL '3 days 14 hours 25 minutes', gen_random_uuid()::text),
  ('KCP Tangerang Villa Melati Mas', 'CAM 3 - Lounge Area', 'Tangerang', 'Tangerang Selatan', 'AFTER_HOURS',         'LOW',    'RESOLVED', 'Detecting activity at a closed branch.',        NOW() - INTERVAL '3 days 5 hours 30 minutes',  NOW() - INTERVAL '3 days 5 hours 27 minutes',  gen_random_uuid()::text),
  ('KC Jakarta Pondok Kelapa',       'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Timur',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        NOW() - INTERVAL '3 days 15 hours 50 minutes', NOW() - INTERVAL '3 days 15 hours 38 minutes', gen_random_uuid()::text),
  ('KCP Jakarta Tomang',             'CAM 1 - Lounge Area', 'Jakarta',   'Jakarta Barat',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        NOW() - INTERVAL '2 days 1 hour',              NOW() - INTERVAL '2 days 40 minutes',          gen_random_uuid()::text),
  ('KCP Jakarta R.S. Pelni',         'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Barat',     'UNAUTHORIZED_ACCESS', 'MEDIUM', 'RESOLVED', 'A customer has entered the Teller area.',       NOW() - INTERVAL '2 days 2 hours',             NOW() - INTERVAL '2 days 1 hour 30 minutes',   gen_random_uuid()::text),
  ('KC Jakarta Pluit Selatan',       'CAM 1 - ATM Area',    'Jakarta',   'Jakarta Utara',     'ATM_LOITERING',       'MEDIUM', 'RESOLVED', 'Someone is at the ATM for an extended period.', NOW() - INTERVAL '2 days 30 minutes',          NOW() - INTERVAL '2 days 10 minutes',          gen_random_uuid()::text),
  ('KCP Jakarta Kelapa Gading',      'CAM 3 - Lounge Area', 'Jakarta',   'Jakarta Utara',     'AFTER_HOURS',         'LOW',    'RESOLVED', 'Detecting activity at a closed branch.',        NOW() - INTERVAL '4 days 16 hours 20 minutes', NOW() - INTERVAL '4 days 16 hours',            gen_random_uuid()::text),
  ('KCP Jakarta Graha Rekso',        'CAM 2 - Teller Area', 'Jakarta',   'Jakarta Pusat',     'FIRE_SMOKE',          'HIGH',   'RESOLVED', 'Smoke or fire appears in the building.',        NOW() - INTERVAL '4 days 16 hours 40 minutes', NOW() - INTERVAL '4 days 16 hours 20 minutes', gen_random_uuid()::text);
